version: '3'

networks:
    dashboard-i:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: ${APP_NAME}_nginx
        ports:
            - "443:443"
        links:
            - dashboardi
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
            - ./docker/nginx/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt:rw
            - ./docker/nginx/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key:rw
            - ./docker/logs/nginx:/var/logs/nginx:rw
        depends_on:
            - dashboardi
        networks:
            - dashboard-i
    dashboardi:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: ${APP_NAME}_fe
        ports:
            - "3000:3000"
        volumes:
            - ./.env:/app/.env:rw
        networks:
            - dashboard-i