version: '3'

networks:
    dashboard-i-prod:

services:
    nginx_prod:
        image: nginx:stable-alpine
        container_name: ${APP_NAME}_nginx_prod
        ports:
            - "4434:443"
        links:
            - dashboardi_prod
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/site-prod.conf:/etc/nginx/conf.d/default.conf:rw
            - ./docker/nginx/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt:rw
            - ./docker/nginx/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key:rw
            - ./docker/logs/nginx:/var/logs/nginx:rw
        depends_on:
            - dashboardi_prod
        networks:
            - dashboard-i-prod
    dashboardi_prod:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: ${APP_NAME}_fe_prod
        ports:
            - "30:3000"
        volumes:
            - ./.env:/app/.env:rw
        networks:
            - dashboard-i-prod
